apiVersion: v1
kind: Service
metadata:
  name: logistic-service
  labels:
    app: logistic
spec:
  type: LoadBalancer
  selector:
    app: logistic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
